add_newline = true
command_timeout = 200
# format = "[$conda$directory$git_branch$git_status]($style)$character"
format = "[$hostname]($style)[$conda$directory$git_branch$git_status]($style)$character"

[hostname]
format = "[$hostname]($style) "
style = "bold red"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"
    
[conda]
symbol = " "  # Optional: Replace with a snake, circle, or custom icon
format = "[$symbol$environment](dimmed green) "
ignore_base = false  # Set to 'true' if you want to hide the 'base' env

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
